language: node_js
node_js:
<<<<<<< HEAD
  - '4.4'
=======
  - 0.10
>>>>>>> cff037e56318987b4e0a30f7990842cf5792fbe2

env: BROWSERS=firefox E2E_BROWSERS=Firefox

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run update-webdriver

script:
  - scripts/private/test-all.sh
